---

- name: install docker
  hosts: webservers
  become: yes
  become_user: root
  tasks:
   - name: update the apt package index
     apt:
        upgrade: yes
        update_cache: yes

   - name: Install list of packages
     apt:
       name: ['apt-transport-https','ca-certificates','curl','software-properties-common','gnupg-agent']
       update_cache: yes
   
   - name: Add Docker GPG key
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg
     
   - name: add repository
     apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

   - name: install docker
     apt:
       name: ['docker-ce','docker-ce-cli','containerd.io']
       update_cache: yes

   
   - name: 'add users to docker group'
     user:
      name: ubuntu
      groups: 'docker'
      append: 'yes'

  handlers:
  - name: Start service docker
    service:
      name: docker
      state: started 
      enabled: yes

   